--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Refaltor77/CustomFurnace-pm4.0.0
build-by-default: true
branches:
- main
projects:
  CustomFurnace-pm4.0.0:
    path: ""
    icon: logo.png
...
